### ISSUE TITLE
The current revision of libcomps cannot be imported in Python 3

### ISSUE THREAD

**Issue by rholy** [midnightercz/libcomps#27]
```sh
$ python3
Python 3.4.3 (default, Jun 19 2015, 10:04:29) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcomps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/libcomps/__init__.py", line 1, in <module>
    from ._libpycomps import *
ImportError: /usr/lib64/python3.4/site-packages/libcomps/_libpycomps.so: undefined symbol: PyInt_Check
```

**Comment by midnightercz** [comment]
Should be fixed in 847f1e60562148a3742b2894fe429a4c0764c188

**Comment by rholy** [comment]
Thanks, seems to work. But now it throws:
```
[...]
    import libcomps
  File "/usr/lib64/python3.4/site-packages/libcomps/__init__.py", line 1, in <module>
    from ._libpycomps import *
ImportError: /usr/lib64/python3.4/site-packages/libcomps/_libpycomps.so: undefined symbol: PyInt_AsLong
```
Should I file another bug report?

**Comment by midnightercz** [comment]
I thought this kind of errors should be discovered by ability to build for both python version, which I did on my local machine and it passed without errors. Maybe latest version of python3 is stripped from some obsoleted stuff. Hopefully d86995b748419bf6ca36f1c7f233727736d2efd5 will fix this.

**Comment by rholy** [comment]
Works, thanks!
